import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const PelangiMedium = localFont({
    src: '/fonts/delight/Delight-Medium.woff2',
    display: 'swap',
    variable: "--font-pelangi-medium"
})
const PelangiRegular = localFont({
    src: '/fonts/delight/Delight-Regular.woff2',
    variable: "--font-pelangi"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PelangiRegular.variable} ${PelangiMedium.variable} antialiased m-0`}
      >
        {children}
      </body>
    </html>
  );
}
